version: '3.7'

services:
  api:
    build: .
    command: uvicorn app.audio_api:app --host 0.0.0.0 --port 8000 --reload

    volumes:
      - .:/usr/src/fusa
    ports:
      - 8000:8000
    depends_on:
      - database
      - rabbitmq

  database:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=fusa
    ports:
      - '5432:5432'

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - database

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  postgres_data: